name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  style:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure branch is up-to-date with main
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin main
          if ! git merge-base --is-ancestor origin/main HEAD; then
            echo "‚ùå This branch is not up to date with main."
            exit 1
          fi

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, bcmath
          tools: composer:v2

      - name: Install Dependencies
        run: composer install --no-scripts --no-interaction --prefer-dist

      - name: Check code style with Pint
        run: |
          vendor/bin/pint --test
          if [ $? -eq 0 ]; then
            echo "‚úÖ Code style is clean"
          else
            echo "‚ùå Code style issues found"
            vendor/bin/pint --verbose
            exit 1
          fi

      - name: Add Lint Results as PR Comment
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            ## ‚ö†Ô∏è PHP Code Style Check Failed

            Please fix the code style issues found by Laravel Pint.
            Run \`composer lint\` locally to see and fix the issues.

            For more information about Laravel Pint, visit: https://laravel.com/docs/pint
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Add Branch Update Reminder as PR Comment
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `
            ## üö® Branch Update Required

            This branch is outdated compared to \`main\`. Please update your branch by merging the latest changes from \`main\`.

            Run the following command in your local branch:
            \`\`\`sh
            git pull origin main
            \`\`\`
            Then push the updated branch to the repository.
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
